export {default as About} from './about'
export {default as Contact} from './contact'
export {default as Intro} from './intro'
export {default as Nav} from './nav'
export {default as Projects} from './projects'
export {default as Work} from './work'
